// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loginResp.proto

package resp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginResp struct {
	Su                   *bool    `protobuf:"varint,1,req,name=su" json:"su,omitempty"`
	Exp                  *int32   `protobuf:"varint,2,req,name=exp" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_loginResp_91a1b7ab3ca5f409, []int{0}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (dst *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(dst, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetSu() bool {
	if m != nil && m.Su != nil {
		return *m.Su
	}
	return false
}

func (m *LoginResp) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginResp)(nil), "resp.loginResp")
}

func init() { proto.RegisterFile("loginResp.proto", fileDescriptor_loginResp_91a1b7ab3ca5f409) }

var fileDescriptor_loginResp_91a1b7ab3ca5f409 = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc9, 0x4f, 0xcf,
	0xcc, 0x0b, 0x4a, 0x2d, 0x2e, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x4a, 0x2d,
	0x2e, 0x50, 0xd2, 0xe5, 0xe2, 0x84, 0x4b, 0x08, 0xf1, 0x71, 0x31, 0x15, 0x97, 0x4a, 0x30, 0x2a,
	0x30, 0x69, 0x70, 0x04, 0x31, 0x15, 0x97, 0x0a, 0x09, 0x70, 0x31, 0xa7, 0x56, 0x14, 0x48, 0x30,
	0x29, 0x30, 0x69, 0xb0, 0x06, 0x81, 0x98, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x45, 0xd1,
	0x24, 0x46, 0x00, 0x00, 0x00,
}
