// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Login struct {
	SKey                 *string  `protobuf:"bytes,1,req,name=sKey" json:"sKey,omitempty"`
	SCode                *int32   `protobuf:"varint,2,req,name=sCode" json:"sCode,omitempty"`
	Mid                  *int32   `protobuf:"varint,3,req,name=mid" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_e3e4167b7b8fd9df, []int{0}
}
func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (dst *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(dst, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetSKey() string {
	if m != nil && m.SKey != nil {
		return *m.SKey
	}
	return ""
}

func (m *Login) GetSCode() int32 {
	if m != nil && m.SCode != nil {
		return *m.SCode
	}
	return 0
}

func (m *Login) GetMid() int32 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

func init() {
	proto.RegisterType((*Login)(nil), "msg.Login")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_login_e3e4167b7b8fd9df) }

var fileDescriptor_login_e3e4167b7b8fd9df = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x72, 0xe6, 0x62,
	0xf5, 0x01, 0x89, 0x09, 0x09, 0x71, 0xb1, 0x14, 0x7b, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x69,
	0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xc5, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x4c, 0x0a,
	0x4c, 0x1a, 0xac, 0x41, 0x10, 0x8e, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x66, 0x8a, 0x04, 0x33, 0x58,
	0x0c, 0xc4, 0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x25, 0x2a, 0x0a, 0xe7, 0x57, 0x00, 0x00, 0x00,
}
